### ISSUE TITLE
How to search an username?

### ISSUE THREAD

**Issue by pedrohenriquebr** [ide-stories/vscode-stories#10]
I want to search someone story by username

**Comment by HariAcidReign** [comment]
> I dont think one can do that for now, cuz it's generating random usernames shown [here](https://github.com/benawad/vscode-stories/blob/334e1d74a3564a40c47188bb4372bffdd1805a32/src/extension.ts#L28)

Is this a recently added feature? Cuz right now all usernames seem to be user-generated.

**Comment by ismaproco** [comment]
you can set the user name going to 

settings > stories 

![image](https://user-images.githubusercontent.com/180197/97778853-c4963500-1b3f-11eb-995f-205a08aa367b.png)

**Comment by HariAcidReign** [comment]
Issue #22 would be of use then, right? @ismaproco

**Comment by TheFern2** [comment]
Yeah searching, and following or pinning some users would be great! :smiley:

**Comment by FluentCoding** [comment]
I've kinda implemented searching (only searches for stories of a specific user in the fetched list) (https://github.com/benawad/vscode-stories/pull/42), and I'll probably take a look at following.

**Comment by TheFern2** [comment]
Closing. Right now @Bukii has implemented friends within the extension based on who you are following on github. I've added searching to the roadmap.
