### ISSUE TITLE
Incomplete username

### ISSUE THREAD

**Issue by Bukii** [ide-stories/vscode-stories#102]
If the length of the username is greater than 8, it just drops the rest. In this example the last "t" of "Test" is missing in the username of the person on the left.
![image](https://user-images.githubusercontent.com/34520811/102287044-e0ac3500-3f39-11eb-897c-9cad27f94351.png)
Maybe add dots.

**Comment by TheFern2** [comment]
Do we want to expand the current limit? If we do we might have to expand the size of the circle.

https://github.com/ide-stories/vscode-stories/blob/3bb9b86242c2957c5daee8c5ecb71b3c301da05f/svelte-stuff/components/StoryBubble.svelte#L78

**Comment by WarenGonzaga** [comment]
I have a better suggestion... add dot's and then add little tooltip hovering the name... I'm working on this right now.

**Comment by TheFern2** [comment]
> I have a better suggestion... add dot's and then add little tooltip hovering the name... I'm working on this right now.

Lemme know if you're still working on this, and I'll reopen.
