### ISSUE TITLE
Poll: Use NPM or Yarn?

### ISSUE THREAD

**Issue by TheFern2** [ide-stories/vscode-stories#106]
There's been some discussion of the issues that having both package-lock.json and yarn-lock.json create. Mainly if a PR uses one over the other, the opposite lock file won't be updated. Whether is easier just to add them to gitignore, and so on. Not having a lock file makes it hard because you don't get the locked deps.

I know the "best practice" for lock files is to check them in the repo, but so should we make the repo contributors use yarn over npm?

👍 for yarn
🚀 for npm
👀 for pnpm

Please use the buttons on this post to vote, and if you have something to add to the discussion please comment.

**Comment by WarenGonzaga** [comment]
what if both yarn and npm? so the user has choice?

**Comment by TheFern2** [comment]
@WarenGonzaga The user can use whatever they want locally, but for the purposes of a PR having two lock files is problematic as one lock file will not be updated at all times. If I don't have yarn installed, and I work on a PR with npm the package-lock.json will be up to date, but not yarn-lock.json, next time someone using yarn does yarn install yarn-lock.json will have thousands of lines updated even though they haven't changed package.json at all. The same issue will occur viceversa for using yarn, package--lock.json won't be up to date.

There is no way to keep one lock in sync with the other easily.

**Comment by TheFern2** [comment]
This [SO](https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files) provides some context. And most answers I've found online is to use only one package manager for projects, mainly because lock files can get out of sync so easily, so then you have to worry about wrong dependency locked trees + git tracking those changes. There's a package https://www.npmjs.com/package/only-allow which enforces users to use certain package manager, but imo that's too drastic, personally I'd like to give users the option to use whatever they want locally since it doesn't affect the project until there's time to submit a PR which has changes to package.json.

So ideally if we end up picking yarn for the projects, we'd put package-lock.json on gitignore, or viceversa. And if a end user choses to use npm that's fine, but at the moment of submitting a PR if there's a change to package.json packages, then we should also get a yarn-lock.json updated file with the PR. Seems like an easy problem to fix but no one has bothered to do it. I might build a module to sync both back and forth.

package-lock.json
```
{
  "name": "vscode-stories-api",
  "version": "1.0.1",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@sqltools/formatter": {
      "version": "1.2.2",
      "resolved": "https://registry.npmjs.org/@sqltools/formatter/-/formatter-1.2.2.tgz",
      "integrity": "sha512-/5O7Fq6Vnv8L6ucmPjaWbVG1XkP4FO+w5glqfkIsq3Xw4oyNAdJddbnYodNDAfjVUvo/rrSCTom4kAND7T1o5Q=="
    },
    "@types/accepts": {
      "version": "1.3.5",
      "resolved": "https://registry.npmjs.org/@types/accepts/-/accepts-1.3.5.tgz",
      "integrity": "sha512-jOdnI/3qTpHABjM5cx1Hc0sKsPoYCp+DP/GJRGtDlPd7fiV9oXGGIcjW/ZOxLIvjGz8MA+uMZI9metHlgqbgwQ==",
      "requires": {
        "@types/node": "*"
      }
    },
```

yarn.lock
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@sqltools/formatter@1.2.2":
  version "1.2.2"
  resolved "https://registry.yarnpkg.com/@sqltools/formatter/-/formatter-1.2.2.tgz#9390a8127c0dcba61ebd7fdcc748655e191bdd68"
  integrity sha512-/5O7Fq6Vnv8L6ucmPjaWbVG1XkP4FO+w5glqfkIsq3Xw4oyNAdJddbnYodNDAfjVUvo/rrSCTom4kAND7T1o5Q==

"@types/accepts@*":
  version "1.3.5"
  resolved "https://registry.yarnpkg.com/@types/accepts/-/accepts-1.3.5.tgz#c34bec115cfc746e04fe5a059df4ce7e7b391575"
  integrity sha512-jOdnI/3qTpHABjM5cx1Hc0sKsPoYCp+DP/GJRGtDlPd7fiV9oXGGIcjW/ZOxLIvjGz8MA+uMZI9metHlgqbgwQ==
  dependencies:
    "@types/node" "*"
```

**Comment by TheFern2** [comment]
So I think we might have an issue with using yarn in the foreseeable future. Yarn 2 was released last year, and that means yarn 1 will now be in sort of maintenance mode or legacy mode. Yarn 2 is not compatible with yarn 1 nor npm projects. Even facebook engineers are saying they might even abandon yarn alltogether and use npm which has made some improvements in the last years.

https://dev.to/arcanis/introducing-yarn-2-4eh1
https://medium.com/@njbmartin/whats-the-problem-with-yarn-2-ca59e3fabc9f
https://shift.infinite.red/yarn-1-vs-yarn-2-vs-npm-a69ccf0229cd

**Comment by TheFern2** [comment]
Yarn is winner, in the next upcoming days I'll be adding package-lock.json to gitignore and adding documentation on how to contribute. I've added to top prio. Locking issue, but not closing until is fixed in the repo.
