### ISSUE TITLE
Stories not working properly

### ISSUE THREAD

**Issue by VivanVatsa** [ide-stories/vscode-stories#107]
![image](https://user-images.githubusercontent.com/56357691/104095492-20f29f00-52bd-11eb-8f47-c3817e4d75b0.png)

This is the error that I have been having trouble with.
I tried switching it to different versions and still, the issue persists
what could be the problem?

**Comment by TheFern2** [comment]
My first guess is that you still have Ben's extension installed, and that would make sense since that server is offline now. You need to install the new one after the repo was transferred to @bar9 Roland. 

![image](https://user-images.githubusercontent.com/10265682/104096309-62556100-5261-11eb-93df-1053a1cff604.png)

The extension is working fine for me right now.

**Comment by TheFern2** [comment]
@benawad @bar9 can you guys come to an agreement and unpublish 2.22.0 extension, just to avoid creating confusion in the future.

**Comment by VivanVatsa** [comment]
@TheFern2 I'm aware of the fact that the whole code has been shifted to the new one and I did install the correct  v2.22.1 from it
still, the same message is displayed, unable to fetch data: error occurred

**Comment by TheFern2** [comment]
Ok, can you give us a bit more information, we can't really help just from the fact that you say is not working on your machine alone. 

- Did it worked previously and now it stopped working?
- Do you have an exact date when it stopped working, if it worked previously?
- OS
- VScode version

Can you try uninstalling it, and installing it again if you haven't already tried that.

Lastly can you try the below in your browser, you should get a json response:

```
https://vscode-stories-295306.uk.r.appspot.com/text-stories/hot
```

**Comment by benawad** [comment]
@bar9 are you good with me unpublishing it?

**Comment by bar9** [comment]
@benawad Yeah, makes sense.
@VivanVatsa can you dm me indicating time and date when you tried loading? I can take a look in the logs, check if I see anything there

**Comment by VivanVatsa** [comment]
@bar9 it might be difficult for me to recall when it actually started to show this behavior, but the problem has been persistent for like 10 days or more now
@TheFern2 I did try reinstalling / uninstalling / removing all versions and then a fair install, still no luck.
* yes it was working before and now it stopped working
* no I don't have any exact/particular info about when it stopped working, really regretting that now
* Windows 10
* vscode v1.52.1

**Comment by VivanVatsa** [comment]
well, I cleared cache memory and optimized by disk space and restarted vscode and it seems to work fine now.
but if the problem arises again will surely let you know @bar9

**Comment by TheFern2** [comment]
> well, I cleared cache memory and optimized by disk space and restarted vscode and it seems to work fine now.
> but if the problem arises again will surely let you know @bar9

Thanks for the info, we'll keep an eye on our windows users.

**Comment by VivanVatsa** [comment]
@bar9

**Comment by VivanVatsa** [comment]
I am experiencing the same problem once again and the time for it is right after my comment of it started working again. I dont know what's the problem, so please help.
so time would be 7 hours ago

**Comment by TheFern2** [comment]
bar9 do you think this is a server issue?

VivanVatsa did you tried calling the api with previous url provided?

**Comment by VivanVatsa** [comment]
yes @TheFern2 I tried that link and still, this message is displayed

![image](https://user-images.githubusercontent.com/56357691/104131599-4951ca80-539d-11eb-8a37-e63844386053.png)

**Comment by TheFern2** [comment]
Yeah I'm beginning to think this issue is related to the changes @bar9 did on the api server during the last week or so.

**Comment by TheFern2** [comment]
Just out of curiosity, both stories panels show fetch error? The sidebar panel, and the small split panel?

**Comment by VivanVatsa** [comment]
can you be precise, which all panel @TheFern2 are you talking about?
their is this "s" logo where I click to see all stories, just the usual way.
that's where this message is displayed. and their is this record story (beta) that's the only 2 things displayed regarding vscode stories

**Comment by TheFern2** [comment]
the s logo is the sidebar panel, but there is also a smaller panel on the file explorer.

![image](https://user-images.githubusercontent.com/10265682/104132016-30ff9280-5340-11eb-93cf-edddda4a2cbf.png)

**Comment by Bukii** [comment]
> Yeah I'm beginning to think this issue is related to the changes @bar9 did on the api server during the last week or so.

But wouldn't that mean, it isn't working for anyone, tho?

**Comment by TheFern2** [comment]
Yeah I dunno what's going on, mine works fine on Linux. I don't use it much at work where I have Windows although I did noticed a very slow fetch one time in Windows.

So it is possible that the fetch is timing out.

**Comment by bar9** [comment]
@VivanVatsa I've increased memory of the database. Did that make any difference on your end? Did you get errors lately?

**Comment by VivanVatsa** [comment]
no luck @bar9 still getting the same error.
accessing from the main extension and the panel. Both display the same error.
really difficult to find what is causing this problem?

![image](https://user-images.githubusercontent.com/56357691/104295110-0e0ee300-54e6-11eb-98fb-e59bb329f4c3.png)


![image](https://user-images.githubusercontent.com/56357691/104295157-19620e80-54e6-11eb-9ed5-deeae33d2c4b.png)

**Comment by TheFern2** [comment]
Can you do the following command in cmd prompt, and post results. Run it a few times just to see if time is really high:

```
ping vscode-stories-295306.uk.r.appspot.com
```

**Comment by VivanVatsa** [comment]
the ping displays:
```
>> ping vscode-stories-295306.uk.r.appspot.com
Ping request could not find host vscode-stories-295306.uk.r.appspot.com. Please check the name and try again.
```

the authentication is working fine when I authenticate it manually as you suggested
but when I try to record and upload it, this is what is displayed even when I have opened a file to record

![image](https://user-images.githubusercontent.com/56357691/104449093-13425f80-55c4-11eb-9a2a-0ffa82004543.png)

**Comment by TheFern2** [comment]
Ok so we have two problems here:

- The ping should definitely ping at all times. Something is wrong with either your firewall or ISP provider. This is really odd.
- If you have a file opened, and is giving you that error that's another weird issue.

**Comment by VivanVatsa** [comment]
did the ping with IP address
the result is this:
![image](https://user-images.githubusercontent.com/56357691/104476887-ba37f300-55e6-11eb-8d3d-76c79cb5504f.png)


for the next step, will use VPN to load stories sure!

**Comment by TheFern2** [comment]
This issue has been resolved.  It looks like @VivanVatsa has some dns issues, but we've added an entry in the hosts file to get the extension working properly, but normally this would not be required if dns was resolving properly to the server address.

**Comment by TheFern2** [comment]
@mrbinary71 can you follow the ping commands on this post. Did you get it sorted out?

**Comment by mrbinary71** [comment]
![Screenshot_2021-01-18_20-48-45](https://user-images.githubusercontent.com/37935734/104945911-9ef62a80-59ce-11eb-807c-938673f415c6.png)

@TheFern2

**Comment by mrbinary71** [comment]
![Screenshot_2021-01-18_20-48-45](https://user-images.githubusercontent.com/37935734/104946045-c2b97080-59ce-11eb-80a0-83fe5580aa32.png)

**Comment by mrbinary71** [comment]
![t1](https://user-images.githubusercontent.com/37935734/104946510-66a31c00-59cf-11eb-8f58-8b6990644365.png)

**Comment by TheFern2** [comment]
It looks like the same issue with dns that Vivan had. This is very strange. 

@bar9 do you think Google has countries in some sort of ban? I wouldn't think so, but we have now two users with dns issues. 

Can you add an entry in /etc/hosts? And try again.

**Comment by mrbinary71** [comment]
I add this entry in /etc/hosts, and It's work fine, thanks.
`216.58.194.52    vscode-stories-295306.uk.r.appspot.com`
@TheFern2

**Comment by TheFern2** [comment]
Nice, you're welcome, I really don't know why dns is not resolving, but we'll try to make a note about this once we setup docs folder in the repo.
