### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by pedrohenriquebr** [ide-stories/vscode-stories#11]
- Issue Type: `Bug`
- Extension Name: `stories`
- Extension Version: `1.2.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 13540,
		"activateCallTime": 3,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "benawad.stories",
				"_lower": "benawad.stories"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by bar9** [comment]
@pedrohenriquebr Is this still an issue with the newest version? https://marketplace.visualstudio.com/items?itemName=bar9.stories
