### ISSUE TITLE
nsfw filter doesnt work

### ISSUE THREAD

**Issue by Milo123459** [ide-stories/vscode-stories#13]
uh the nsfw filter doesnt work on the extension

**Comment by Milo123459** [comment]
@benawad Probably not the right place to ask but, in the API is there ever an instance of the gif as a buffer? In the post route Im trying to test for NSFW content but cant find the actual story

**Comment by benawad** [comment]
I'm dm on discord

**Comment by Milo123459** [comment]
Submitted my pr! Would appreciate any reviews:
https://github.com/benawad/vscode-stories-serverless-image-uploader/pull/3

**Comment by JonnyBeoulve** [comment]
Hi YouTube.

**Comment by khaledosman** [comment]
The internet is a beautiful place, why ruin it with censorship? Kappa

**Comment by bar9** [comment]
closing for now, in case we bring back GIFs it would be part of that issue
