### ISSUE TITLE
Recording stops after est. 1 milisec.

### ISSUE THREAD

**Issue by Flubio** [ide-stories/vscode-stories#16]
![image](https://user-images.githubusercontent.com/46036162/97754463-da800780-1af7-11eb-86d1-ee216a2d9f97.png)

The error is shown directly after the pre countdown is finished

OS: `Windows_NT x64 10.0.19041`
VSC: `Version 1.50.1`

**Comment by bar9** [comment]
@Flubio What's the status of this bug (since recording has changed quite a bit)? Does it still occur with the newest version?

**Comment by Flubio** [comment]
> @Flubio What's the status of this bug (since recording has changed quite a bit)? Does it still occur with the newest version?

No it doesn't occur anymore 👍
