### ISSUE TITLE
can't record anymore :/

### ISSUE THREAD

**Issue by gustavoFreireS** [ide-stories/vscode-stories#18]
I received this message when I tried to record something:

<img width="470" alt="Captura de Tela 2020-10-30 às 22 15 57" src="https://user-images.githubusercontent.com/8769796/97767841-98f25b00-1afd-11eb-996a-29379ea8675a.png">

**suggestion**: use something like this to verify if the image/gif is NSFW
https://github.com/infinitered/nsfwjs

**Comment by TheFern2** [comment]
He's already using that, and not working very good. I can't believe people can't act like adults.

**Comment by findtravishere** [comment]
this is why we can't have nice things. dumb kids thinking they're funny. at least it means we get more improvements for this extension
