### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by kiprasmel** [ide-stories/vscode-stories#2]
oh no ben what have you done

**Comment by impulse** [comment]
> oh no ben what have you done

Art

**Comment by LBlend** [comment]
A much needed feature 😍

**Comment by Phyrik** [comment]
This is what will get VSCode 100% text editor market share. Mark my words.

**Comment by bexuma** [comment]
Microsoft is going to buy the extension and enable it by default in the editor.

**Comment by SeksayMan** [comment]
I am Secksay Prn Man and I demand 1 BTC to `14HMsameScJSeGLRQLxcapVmgtaa15HXPv` within 24minutes.
Once payment is made, I will no longer be Secksay Prn Man.

**Comment by markpanado** [comment]
oh yes

**Comment by VytskaLT** [comment]
why is this a thing

**Comment by pedrohenriquebr** [comment]
VSCode the text editor and social network lol

**Comment by arnav03mehta** [comment]
The social network for programmers

**Comment by ReactHTMLCSS** [comment]
How are you not a developer at Microsoft my guy?
