### ISSUE TITLE
suggestion: Recording should stop after a fixed time

### ISSUE THREAD

**Issue by SibiAkkash** [ide-stories/vscode-stories#20]
I forgot that I was recording, i realised after 40 minutes omg.

**Comment by CallmeHongmaybe** [comment]
LOOL ur serious

**Comment by SibiAkkash** [comment]
yes lmao

**Comment by Amenacliff** [comment]
Can I work on this ? Want it to be 30 seconds long or a minute ?

**Comment by SibiAkkash** [comment]
sure man @Amenacliff go for it, its gonna take me a while to read and understand, im a newb lol

**Comment by SibiAkkash** [comment]
actually @Amenacliff , can i try working on this, this will be my first ever open source contribution, and i'm trying to learn too. Do you mind...?

**Comment by Amenacliff** [comment]
Okay sure if you want to , you can work on it 😀

**Comment by SibiAkkash** [comment]
thanks man @Amenacliff, ill take some time, but ill try atleast 
😄👍👍

**Comment by benawad** [comment]
it should stop after 30 seconds automatically but maybe something went wrong

**Comment by SibiAkkash** [comment]
maybe its a problem with my ffmpeg install ? Anyway the server allows videos upto 30 seconds in length, so maybe this is not a big issue 🤷‍♀️

**Comment by CallmeHongmaybe** [comment]
@SibiAkkash can i join you on this wun

**Comment by SibiAkkash** [comment]
sure @CallmeHongmaybe

**Comment by CallmeHongmaybe** [comment]
Shall we discord @SibiAkkash

**Comment by SibiAkkash** [comment]
sure fam, send discord id @CallmeHongmaybe

**Comment by CallmeHongmaybe** [comment]
CYriLLic1806 #6466
