### ISSUE TITLE
Excuse me but how is this useful or kinda entertainment? 

### ISSUE THREAD

**Issue by tomavic** [ide-stories/vscode-stories#24]

**Comment by Tiberriver256** [comment]
Watch his other YouTube videos. It was a joke. A very sarcastic dry joke. That a lot of people actually turned out to enjoy, lol.

**Comment by anubra266** [comment]
Well it's a start, could become an actual developer circle in vscode, on improvements

**Comment by TheFern2** [comment]
I mean if is not useful or entertaining, why are you here? Just don't download the extension.

**Comment by tomavic** [comment]
@TheFern2 that's a typical answer for such question, not A REAL answer why you can find this useful.

**Comment by anubra266** [comment]
@tomavic It's as useful as any Social Network, if only you'll try to help its progress.

**Comment by tomavic** [comment]
@anubra266 Yeah I'd like to invest time to do this for sure. I believe that our job is not that much social even if we working with team. As we all working from home and apart from each other. 

This is the only way I can see this useful.

**Comment by TheFern2** [comment]
@tomavic Well your question was poorly written and you provided no details on the description other than the title. Are you asking why it can be useful or entertaining? Or are you saying that you didn't find it useful or entertaining? A bit of context can get you a long way. 

- entertainment and useful is subjective so what one finds useful might be the same for you.

**Comment by tomavic** [comment]
@TheFern2 Oh yeah! the context was not clear. What I meant, how could you find it useful for you? You know I could build features that are widely popular such as stories into any app, but does it worth it, or just to let people know that you are the one who can build anything to anything and make it work!

**Comment by TheFern2** [comment]
@tomavic Tbh I use Instagram and I personally don't even look at people's stories there.

For me is interesting because you can share a bit of code with the community, instead of making a tweet.

If you can build anything into any app do it, and if people like it then you'll be a king. Here Ben took a gamble and he got nearly 10K downloads in a few days I called that a very well liked extension on my books.

**Comment by tomavic** [comment]
@TheFern2 I believe that, not only building anything to any app is the major here, but the most important is how many followers you have to make the bang.

**Comment by bar9** [comment]
Highly interesting discussion, something that occupied my mind as well (and still does). I'm still closing the issue for housekeeping purposes. Let's take this to social media though: https://twitter.com/RolandBrand5/status/1331863776845553664

**Comment by dragonDScript** [comment]
While this started as a joke, I would love having some kind of social network inside VSCode (like this one!)
