### ISSUE TITLE
Add feature: GitHub authentication

### ISSUE THREAD

**Issue by Satak** [ide-stories/vscode-stories#26]
Add feature to authenticate with GitHub and use your GH as the username. Also search for users is needed to friend them. GitHub groups could be used as filters too.

**Comment by YazeedAlKhalaf** [comment]
VS Code has the authentication built-in for syncing settings so I guess there is some API exposed to do so ✨

**Comment by kurtextrem** [comment]
Would also make it easier to ban people uploading nsfw stuff.

**Comment by Bobj2018** [comment]
Yes, that would be a great start to tackle the NSFW content as most developers SHOULD have github. Of course, we would have a few that would troll, but it will make it easier to take care of the problem.

**Comment by HariAcidReign** [comment]
https://github.com/benawad/vscode-stories-api/issues/7#issuecomment-720120604

I too feel that a Github OAuth would solve most of the NSFW username issues. #22 
I would like to work on the OAuth part w someone if that is viable. 😄

**Comment by Bukii** [comment]
Since you have to authenticate with your GitHub acc now, I guess this should be closed now.
