### ISSUE TITLE
How do I follow someone or see people's stories?

### ISSUE THREAD

**Issue by okumo** [ide-stories/vscode-stories#4]

**Comment by shanjng** [comment]
Worrd I'm tryna do that

**Comment by DavidMunozMartinez** [comment]
Currently the extension uses a user name defined in the settings, and there is no "follow" feature, at the its current state you can see everything that is posted by everyone

**Comment by Avi98** [comment]
related to #4

**Comment by Avi98** [comment]
related to #10

**Comment by bar9** [comment]
closing, will follow up under #10
