### ISSUE TITLE
Suggestion: delete this for the good of humanity

### ISSUE THREAD

**Issue by hormelcookies** [ide-stories/vscode-stories#40]
It's starting as a joke, but it will rapidly become unironic and it will be terrible. Delete this before it happens and save us all from the horror that will inevitably follow.

**Comment by anubra266** [comment]
People like you give me the strength to continue when I'm discouraged.
But I actually wonder why u're on github or how you found ur way here

**Comment by HerrEurobeat** [comment]
Suggestion: Better close this issue before more thumbs down come in...
