### ISSUE TITLE
Move Forward

### ISSUE THREAD

**Issue by anubra266** [ide-stories/vscode-stories#41]
I don't care what others are saying. I love this
It brought smiles to my face.
You could make it a league kind of thing, instead of General, so users can only see those they follow.

**Comment by TheFern2** [comment]
Yeah the idea is solid af. Just need to clean up the rough edges.

**Comment by anubra266** [comment]
Thank God!
Here is [someone](@TheFern2 ) Who sees things for what they could become

**Comment by bar9** [comment]
Kickstarter campaign starting soon: https://www.kickstarter.com/projects/rolandbrand/vs-code-stories
If this succeeds, we can turn this into a sustainable platform.

**Comment by anubra266** [comment]
@bar9 I'll love to help in any capacity I can.

**Comment by TheFern2** [comment]
@anubra266 are you still interested in helping out?

**Comment by anubra266** [comment]
yes I am @TheFern2

**Comment by TheFern2** [comment]
Ok, I'll let @bar9 know and perhaps we can have another team member after the holidays. Cheers!

**Comment by anubra266** [comment]
Thanks! Happy to help. @TheFern2

**Comment by bar9** [comment]
@anubra266 awesome, I'm adding you to the discord group

**Comment by anubra266** [comment]
Hi! @bar9  My Discord Invite link is invalid.

**Comment by Bukii** [comment]
> Hi! @bar9  My Discord Invite link is invalid.

@anubra266 I've sent you a new one on Twitter DMs.
