### ISSUE TITLE
Failed to Fetch?

### ISSUE THREAD

**Issue by NateAGeek** [ide-stories/vscode-stories#5]
Hello, I keep getting a failed to fetch error onload... Maybe attach an error code to give more insight. I think you can also pipe data into an output screen on Visual Studio Code that could contain errors.

<img width="549" alt="Screen Shot 2020-10-30 at 10 04 39 AM" src="https://user-images.githubusercontent.com/1813055/97721649-b42a7f80-1a97-11eb-98dd-bde273d7b2e9.png">
<img width="514" alt="Screen Shot 2020-10-30 at 10 04 45 AM" src="https://user-images.githubusercontent.com/1813055/97721653-b55bac80-1a97-11eb-8bb7-00aad961c8fb.png">

**Comment by ablil** [comment]
I'm having the same problem, It would be great to display error message instead of `Failed to fetch`, and of course fix the bug

**Comment by SeksayMan** [comment]
Because Seksay Prn Man is here.

**Comment by SeksayMan** [comment]
I am Secksay Prn Man and I demand 1 BTC to `14HMsameScJSeGLRQLxcapVmgtaa15HXPv` within 24minutes.
Once payment is made, I will no longer be Secksay Prn Man.

**Comment by kiprasmel** [comment]
yep. from the vscode's devtools, it seems like it'd be a CORS issue?

![image](https://user-images.githubusercontent.com/29430509/97722818-c1fdf600-1ad3-11eb-9e5a-1258661f2661.png)

```console
webviewElement.ts:150 [Embedded Page] Access to fetch at 'https://bowl.azurewebsites.net/stories/hot' from origin 'vscode-webview://webviewview-stories-full' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

the fetch url itself seems broken:

https://bowl.azurewebsites.net/stories/hot

![image](https://user-images.githubusercontent.com/29430509/97722919-dd690100-1ad3-11eb-8e5c-e40776d7247b.png)

**Comment by SeksayMan** [comment]
You silly goose, check his twitter - he had to take it down because some troll was posting stuff.

**Comment by kiprasmel** [comment]
oof

https://twitter.com/benawad/status/1322189944803282947

**Comment by CallmeHongmaybe** [comment]
I'm having the same error when I click the icon on the side bar.

**Comment by bar9** [comment]
@NateAGeek @kiprasmel @alago1 @esokoloff @maskeyhinal @ablil @CallmeHongmaybe Is this still an issue with the newest version? https://marketplace.visualstudio.com/items?itemName=bar9.stories

**Comment by maskeynihal** [comment]
@bar9 I am not having this problem. IMO, this is solved. :tada:

**Comment by NateAGeek** [comment]
Thank you :) and good luck with the project 👍

**Comment by evclid** [comment]
![image](https://github.com/user-attachments/assets/0485f336-8d7a-410a-aa37-d1585e9bd349)
Есть те кто смог решить проблему?
