### ISSUE TITLE
[Feature Request] An option to delete own story

### ISSUE THREAD

**Issue by DaijobuDes** [ide-stories/vscode-stories#52]
As the title says, would be nice to place a delete option on our own stories in case something that was not meant to be shared in the stories or a mistake was made.

And I saw someone said "how to delete stories"

![image](https://user-images.githubusercontent.com/38452446/97810357-2ecce800-1cae-11eb-9998-65418686c366.png)

**Comment by St3f4NS** [comment]
Yeah, I think this one is needed. I didnt know about update, accidentally uploaded a file to story. Not a biggie, but still random file got uploaded :D 
SOMEONE PLS UPLOAD .ENV FILE :D

**Comment by bar9** [comment]
@DaijobuDes delete is working except for the confirmation message/refresh needed.
