### ISSUE TITLE
Add donation link

### ISSUE THREAD

**Issue by St3f4NS** [ide-stories/vscode-stories#59]
This was just a stupid fun idea at the start, now it can be really useful thing for people. 

So, I think we need some way of supporting it, donation link for a start. Later on, pro features.

**Comment by bar9** [comment]
@St3f4NS  @IJustDev @TheFern2 @henryboisdequin @Phyrik @anubra266 
Here you go: [Kickstarter campaign starting soon](https://www.kickstarter.com/projects/rolandbrand/vs-code-stories)
Thanks for your support, and please spread the word.
Imho in order for this to be really useful there's still a lot to do, especially with the new text stream format which currently feels more like a telegram than code.
