### ISSUE TITLE
Stories don't work on Windows->WSL (via RemoteWSL extension)

### ISSUE THREAD

**Issue by Iipal** [ide-stories/vscode-stories#61]
![image](https://user-images.githubusercontent.com/31858171/97818569-cd0b7e80-1cab-11eb-96d0-5d1f8d7ecf46.png)

**Comment by Oxicode** [comment]
Pensé q era error mío :S

**Comment by grovertb** [comment]
+1

**Comment by benawad** [comment]
could you toggle developer tools from command palette and see if there's an error

**Comment by Iipal** [comment]
@benawad 
![image](https://user-images.githubusercontent.com/31858171/98355618-0c7af780-202b-11eb-91ac-e0c0d1830c0f.png)

only this

**Comment by benawad** [comment]
That's an ok warning, can you try opening the webview developer tools from command palette and see if there's anything in there? Also check the network tab to see if the request works ok and gets data.

**Comment by Iipal** [comment]
@benawad can't open webviews dev.tools at all

**Comment by benawad** [comment]
interestingly enough if you click on the S in the sidebar:
![image](https://user-images.githubusercontent.com/7872329/98388474-71792200-2018-11eb-9a03-b3e87d50fd41.png)
that seemed to work for me, then clicking back to the other panel and closing/opening it got it to work.

For some reason the first time the webview loads it can't find the script/css files but then they show up ??

**Comment by Iipal** [comment]
@benawad yeah, by chaotically clicking on the icon on the sidebar and on the window on explorer really works for me too. seems like a good solution for this issue xd

**Comment by bar9** [comment]
@Iipal what's the state on this? There was another issue on Ubuntu, maybe this is fixed by now?

**Comment by Iipal** [comment]
@bar9 yeah, seems like it's working now just perfect
