### ISSUE TITLE
Prioritize stories with 'follow' 

### ISSUE THREAD

**Issue by EightRice** [ide-stories/vscode-stories#67]
Use case: I have some coders that I appreciate and would like to find their stories when I start my work, for additional inspiration motivation and all that good stuff. But I don't want to search in that (seemingly endless) list.
Set own story as first in list, and introduce a 'follow' option to prioritize the stories. Potentially even create a visual separation of stories from followed users vs non-followed users. You could desaturate the profile pics of non-followed users.

**Comment by RealDyllon** [comment]
I suppose we could make use of github's following api instead of building something separately.

**Comment by breadnone** [comment]
Ideally I would follow people that specifically related to their repo or anything related to my job (my work colleague). This feature will mess everything up

**Comment by Bukii** [comment]
Hey, I made a PR for following users. Unfortunately, there isn't a separated section, where you can only see those people, you have followed. But I will continue to look into it, and hopefully add that. Also, using the GitHub API to show your GitHub friends as well, is a nice idea. I would love to try this. :)

**Comment by bar9** [comment]
@Bukii cool, thanks a lot for this. Will review this asap.

**Comment by TheFern2** [comment]
> Hey, I made a PR for following users. Unfortunately, there isn't a separated section, where you can only see those people, you have followed. But I will continue to look into it, and hopefully add that. Also, using the GitHub API to show your GitHub friends as well, is a nice idea. I would love to try this. :)

Yup we need to add a filter to the stories panels, or maybe even next to the refresh button. We'll try to test the github friends route sometime this week.

**Comment by Bukii** [comment]
This idea is now implemented in v2.23.0 - this version will be released as soon as possible.
