### ISSUE TITLE
Change color of the circle of the stories

### ISSUE THREAD

**Issue by JoseDeFreitas** [ide-stories/vscode-stories#75]
Hello 👋.
I was wondering if the color of the circle of the stories could be changed, as this gradient looks like Instagram's one and doesn't fit with the common VScode themes.
I made a circle blue gradient (same colors as VScode logo) just to show an example:

![vscode-stories-new-color-circle](https://user-images.githubusercontent.com/37962411/98470992-3f51f680-21b7-11eb-8552-5196402c98a2.png)

I know this started as a joke and probably the intention of the color is to be like Instagram's one. If that's the case close this issue, but I thought maybe would be a cool change.

**Comment by benawad** [comment]
I'll merge if you want to PR

**Comment by WarenGonzaga** [comment]
Ow I like it... @benawad is the project can cause performance issues?

**Comment by benawad** [comment]
not that I'm aware of

**Comment by JoseDeFreitas** [comment]
May this issue be closed?
