### ISSUE TITLE
Not loading stories

### ISSUE THREAD

**Issue by stringie** [ide-stories/vscode-stories#8]
![stories](https://user-images.githubusercontent.com/23170702/97732523-50c44000-1adf-11eb-9c13-ca6cfe4ae89b.png)

Nothing is getting loaded. It's like it's not making a request.

**Comment by bar9** [comment]
@stringie @benedikt-mayer @simonkurek is this still an issue with the newest version? https://marketplace.visualstudio.com/items?itemName=bar9.stories

**Comment by benedikt-mayer** [comment]
works for me 👍
