### ISSUE TITLE
I sold this extension | New Maintainer

### ISSUE THREAD

**Issue by benawad** [ide-stories/vscode-stories#82]
I have sold VSCode Stories to @bar9 and he will be taking over this codebase.

More info: [https://youtu.be/CHO316LKnZw](https://youtu.be/CHO316LKnZw)

**Comment by TheFern2** [comment]
Kinda bummed about it, but I will continue to contribute anyways. Glad you got paid!

**Comment by TheFern2** [comment]
@bar9 can you comment a bit on the direction you're planning on taking. I literally just had finished setting up my local environment to work on the ban system, but now wondering if I should just wait and see what happens with Ben's repos.

**Comment by WarenGonzaga** [comment]
@TheFern2 that's the future! Lol

**Comment by TheFern2** [comment]
> @TheFern2 that's the future! Lol

Ngl extensions if done right is a good business just the other day I was listening to a podcast about gitduck extension.

**Comment by WarenGonzaga** [comment]
@TheFern2 the gitduck is so cool!

**Comment by TheFern2** [comment]
Not sure what the future holds for vscode-stories, but I have made a fork [vscode-shares](https://github.com/TheFern2/vscode-shares) where I intend to keep this extension open source since code was written under MIT license. If @bar9 doesn't have intention of oss, then I will add changes on my repo, and push a new extension to marketplace.

```
MIT License

Copyright (c) 2020 Ben Awad

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
...
```

**Comment by WarenGonzaga** [comment]
@TheFern2 good move! How about server expenses?

**Comment by TheFern2** [comment]
@WarenGonzaga I can probably pitch for the first few months, and probably put a server tip meter on the extension so people can donate for server costs.

We'll see what direction this extension goes first though.

**Comment by WarenGonzaga** [comment]
@TheFern2 awesome! I will watch it on it and support it!

**Comment by bar9** [comment]
@TheFern2 and other contributors: I would like to get in touch with you guys. VSCode Stories **will definitely stay open source**. I also like the idea of expanding this to other IDEs, but have no concrete plans for that as the next steps. I'll go out with a kickstarter campaign next week with the goal of financing the next steps of development of stories. I intend to follow the voice of the community, and put in some extras like sponsored channels or language groups, to give incentive to founders. I will probably work with freelancers as well. In case of a successful funding, this could also mean paid work for core contributors. I'm kind of new in this business, but here's my philosophy behind it: [OSBoost](https://www.osboost.com/)

**Comment by WarenGonzaga** [comment]
Thanks, @bar9 for your response and we really appreciate that you have that kind of philosophy kind of like Issuehunt.

**Comment by TheFern2** [comment]
@bar9 Nice! I always thought oss to be cool as hell but severely underpaid especially for code that helps the community. If it gets a successful funding, and I think it will, it would be nice to do something like bounty rewards  program. Something like this
 https://dev.to/rudderstack/devs-wanted-get-paid-to-contribute-to-rudderstack-s-open-source-software-bjp

Github should have already implemented a system for bounties, the sponsorship system isn't the greatest imo.

Feel free to reach me @ fernandobe+git@protonmail.com

**Comment by pranavnt** [comment]
@benawad You need to add "(as an ex-CEO)" to your video titles.
