### ISSUE TITLE
Counting likes (-)

### ISSUE THREAD

**Issue by LeonardSSH** [ide-stories/vscode-stories#88]
Small bug when counting likes.

![ezgif-1-84e84a55ac40](https://user-images.githubusercontent.com/35312043/99397860-e59eaa00-28e3-11eb-9907-c0c34af40987.gif)

**Comment by TheFern2** [comment]
I believe this is an issue with the api, if I add a bit of latency to the middleware and click really fast, the database throws duplicate key errors, and then the ui goes haywire. I think we need to add some rate limiting on those routes to prevent database errors.

![image](https://user-images.githubusercontent.com/10265682/102170461-0f52de80-3e5a-11eb-92e3-9199fc83c9b2.png)
