### ISSUE TITLE
Keyboard shortcuts clash with the 'save all' shortcut

### ISSUE THREAD

**Issue by moderatemisbehaviour** [ide-stories/vscode-stories#89]
I'm no longer able to save all on MacOS using the default keyboard shortcut `alt + shift + s`. This is because the shortcuts for this extension use `alt + shift + s` as part of thei 'chord' shortcuts.

**Comment by Bforsyth1234** [comment]
THIS drove me nuts....

**Comment by bar9** [comment]
This can be easily changed in the Keybindings section of package.json
What would you suggest instead?
Does anyone use the keybindings?

**Comment by moderatemisbehaviour** [comment]
@bar9 
> This can be easily changed in the Keybindings section of package.json
I understand but that pushes the responsibility of thinking of many keybindings for the supported functionality onto me the user rather than the developer - one person can save everyone else a lot of time here. Personally the effort of changing them alone was enough for me to disable the extension and wait for an update rather than take up my own time, just giving the honest feedback 🙂 

> What would you suggest instead?
Default keybindings that don't clash with the IDE's default keybindings.

> Does anyone use the keybindings?
I do? If you are asking about most people then I'm not sure. If you don't think keybindings are very important for this extension (which I'd agree with) then it would be much better to ship with no keybindings at all than to break VS Code's default ones.

**Comment by Bukii** [comment]
What about changing the keybindings individually in the vscode settings? Default would be null then. For those people that want to use keybindings, they can set it by their own.

**Comment by Bforsyth1234** [comment]
I think @Bukii has the right idea. Make them null for the extension. If someone wants to add them they can add them to a keybinding of their choice. 

Also even if it can be changed in the package.json, it's of a poor user experience to break the default settings in vs code and leave it to the user to figure out which extension broke it and how to fix it.

**Comment by bar9** [comment]
I agree, nulling is a good plan. I shouldn't have mentioned package.json, i didn't mean that the user has to change it there, but that it is an easy change for me or another devleoper
