### ISSUE TITLE
Overtyping/Incorrect Text in Story Output

### ISSUE THREAD

**Issue by piccoloser** [ide-stories/vscode-stories#90]
Anything that is filled in by a code snippet (eg. using the `!` shortcut in Emmet) is overwritten by whatever the user types when they tab through values. This only appears in the story replay.

### What was shown in the replay:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<bod<!-- >Test --> See?
    
</body>
```
_Note: I changed the_ `<title>` _to "Test," but the value somehow ended up cutting into the_ `<body>` _tag._

### What I actually wrote:
```html
<!-- There's an overtyping bug when you use Emmet -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <title>Test</title> See? -->
</head>
<body>
    <!-- p{This is a test} It happens here too. -->
</body>
</html>
```

**Comment by bar9** [comment]
Same for autocomplete and e.g. Vim Plugin

**Comment by bar9** [comment]
Same issue: #86

**Comment by Bukii** [comment]
Same issue: #127
But I will close this one, since #127 is better documented.
