### ISSUE TITLE
Bring frontend and backend repos together?

### ISSUE THREAD

**Issue by bar9** [ide-stories/vscode-stories#91]
I'm open to discuss this.
Reasons to merge: Syncing versions is much easier, also for PRs.
Reasons to keep separate: API would stay open to no matter what frontend (e.g other IDEs)

Thinking about this because of https://github.com/ide-stories/vscode-stories-api/pull/14

Thoughts?

**Comment by Bukii** [comment]
I would like to keep it separate, since it's uncluttered and more manageable. Also, if @MoathAlshorman really wants to make an IntelliJ version, it is best to keep it as it is, imo.

**Comment by bar9** [comment]
Sounds fair
