### ISSUE TITLE
Use design elements from JessicaDosseh

### ISSUE THREAD

**Issue by bar9** [ide-stories/vscode-stories#98]
@JessicaDosseh you sent me this potential design a few weeks ago. Can we still use it? Are you planning to contribute more on this?

[Design GIF](https://ksr-ugc.imgix.net/assets/031/449/061/628508189962aa683e58844068f1d735_original.gif?ixlib=rb-2.1.0&w=700&fit=max&v=1605643862&auto=format&gif-q=50&q=92&s=e9e19ceec6c132c8abb8ecff1b13a28f)

**Comment by TheFern2** [comment]
That is very cool, nice and clean design!

**Comment by JessicaDosseh** [comment]
@bar9 Yeah, you're free to use it. Just let me know what you need.

**Comment by TheFern2** [comment]
@bar9 we prob should have let @JessicaDosseh commit the logo onto the repo for proper credit.
Will give her credit on the readme.

**Comment by TheFern2** [comment]
@JessicaDosseh I've added an easter egg to the code inside [constants.ts](https://github.com/ide-stories/vscode-stories/blob/master/src/constants.ts) I tried adding you as coauthor in the readme and you weren't showing up as contributor. I wanted to make sure you got credit for the logo.

![image](https://user-images.githubusercontent.com/10265682/106511342-b71d7d80-6495-11eb-8d40-edab2a0b6f8b.png)

![image](https://user-images.githubusercontent.com/10265682/106511386-c43a6c80-6495-11eb-9fcc-dc9c375f8c6f.png)
